default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: basejump_development
  prepared_statements: false
  reaping_frequency: 10

  # Use Supabase local connection if DATABASE_URL is set
  url: <%= ENV['DATABASE_URL'] %>

test:
  <<: *default
  database: basejump_test

production:
  <<: *default
  database: basejump_production
  url: <%= ENV['DATABASE_URL'] %>